### PR TITLE
Enhancement/Add dark mode

### LINKED ISSUE #3: Feature Request: Dark Mode
(To anyone else reading: I know Olavi and this a half-joke, and an intent to implement. I wouldn't write this otherwise :sweat_smile: )

**Is your feature request related to a problem? Please describe.**
Finland is a dark place in the winter, I am a shady person, and the light burns my eyes.
I think a dark mode would be dank. :city_sunset: :100: :fire:

**Describe the solution you'd like**
I think you can do this purely with CSS custom properties, and their propagation.
Adding the button in an accessible spot, and in an accessible manner, would also be important.

**Describe alternatives you've considered**
You could also do this more heavy-handedly with `style="..."` or with bare CSS classes, but that solution is a bit more brittle, since you have to propagate the context of light/dark mode.

**Additional context**
I want to implement this! I will send a PR your way if you're ok with it.

### PR DESCRIPTION
**Pull request by fpapado**
Closes #3 :tada:

## What was done
- Added a Theme module that contains types and functions relevant to the theme
- Added `viewThemeToggle` to the Main file, which is a button that toggles between Light and Dark mode
- Added `Html/A11y.elm` for some helper functions that help communicate the button state to assistive technology. Elm's module system is fun because allows you to import these as `Html.A11y`!
- Added the moon icon from `feathericons/elm-feather`
- Some general CSS changes to make the containers behave better.

## Decisions, questions
- The dark theme was sort of arbitrary, and not thought through completely. In particular, I'd rather we highlighted the "Yes/No" parts better, instead of the question. That goes for the Light theme too, though, which is why I left it as-is
- I initially had the theme button as text-only. I guess both that and the icon are valid.
- Should we just position the button on the top right?

## Future ideas
- It would be cool to save the user's preferences to localStorage, and load them on init. I'd tackle this in another PR, after re-organising some of the model a little :)
- I should fork / make a PR to feathericons for them to handle the accessibility of the SVG through types. SVG can be either "Standalone" or "Decorative", and it would be cool if the user didn't have to think other than that. Similar to what I did for react-feather github.com/fpapado/react-feather.

## Screens
screen shot 2018-10-14 at 15 31 45
screenshot_2018-10-14 onko metro rikki

### CODE REVIEW

**Comment by olpeh** [comment]
Thank you @fpapado!
Will take a closer look soon, but just wanted to comment out that having Now deploy PRs to staging env is pretty damn cool feature. Helps testing new features easily. https://onkometrorikki-odguralmgo.now.sh/

**Comment by olpeh** [comment]
This looks pretty good to me @fpapado. Thank you. And as you mentioned we should save the preferences locally in a separate PR. Related to that, when implementing #5 it should also save the preferred language locally.

>Should we just position the button on the top right?

I'd say the position is fine as it is now. We can always fix it later. And probably will when implementing #4, which should add a refresh button as well. 

However, I have 2 nitpicks/ideas/suggestions:

- Somewhat annoying focus/outline visible on Firefox, see screenshot below
- Everything else switches color except the top-bar on Android. Would it be possible to (re-)set the theme-color meta tag dynamically when switching theme? Would be cool, but don't know if doable.

photo_2018-10-15_09-36-02

image

**Comment by olpeh** [comment]
screenshot_20181015-163516
The contrast on the reason text is not very high as you can see from the screenshot.

**Comment by fpapado** [comment]
@olpeh, I got the theme-color change working for the banner, and the button now has proper outlines, and not the annoying Firefox thing.

I'll check the main text contrast, thought I was missing something!

**Comment by fpapado** [comment]
Fixed now :sparkles:

Damn, the now previews are *fast*

screenshot_2018-10-15 onko metro rikki

**Comment by olpeh** [comment]
Thanks @fpapado :tada:

**Pull request merged**
